batch_size: 1
decoder_name: mlp_decoder_base
dist_backend: nccl
dist_url: env://
gpu: 0
iters: 1000000
learning_coef: 1.0
learning_rate: 0.0001
log_interval: 10
metas_path: /home/fyc/EmpiricalStudyForVLA/datasets/meta_files/robotwin.jsonl
model_type: flow-matching
num_actions: 10
output_dir: runnings/RoboTwin
port: 13555
precision: fp16
pretrained: null
rank: 0
resume: null
save_interval: 20000
seed: 0
vision_backbone: resnet18.a1_in1k
weight_decay: 0.01
world_size: 2
